# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode8
script:
- xctool test -project SwiftHEXColors.xcodeproj -scheme SwiftHEXColors -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
